# Generated by Django 4.1.5 on 2023-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taks',
            name='Datecompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
